-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 20:42:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbCinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbCinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbCinema` DEFAULT CHARACTER SET utf8 ;
USE `dbCinema` ;

-- -----------------------------------------------------
-- Table `dbCinema`.`tbFilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbFilm` (
  `film_id` INT NOT NULL AUTO_INCREMENT,
  `film_judul` VARCHAR(45) NULL,
  `film_deskripsi` VARCHAR(400) NULL,
  `film_poster` VARCHAR(150) NULL,
  `film_trailer` VARCHAR(400) NULL,
  `film_sutradara` VARCHAR(45) NULL,
  `film_aktor` VARCHAR(400) NULL,
  `film_durasi` VARCHAR(45) NULL,
  `film_rating` VARCHAR(45) NULL,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbMember` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `member_username` VARCHAR(100) NULL,
  `member_password` VARCHAR(100) NULL,
  `member_email` VARCHAR(100) NULL,
  `member_nama_depan` VARCHAR(100) NULL,
  `member_nama_belakang` VARCHAR(100) NULL,
  `member_photo` VARCHAR(100) NULL,
  `member_saldo` DOUBLE NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbStudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbStudio` (
  `studio_id` INT NOT NULL,
  `studio_nama` VARCHAR(45) NULL,
  PRIMARY KEY (`studio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbJadwal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbJadwal` (
  `jadwal_id` INT NOT NULL,
  `jadwal_tanggal` DATE NULL,
  `jadwal_sesi` INT NULL,
  `tbFilm_film_id` INT NOT NULL,
  PRIMARY KEY (`jadwal_id`),
  INDEX `fk_tbJadwal_tbFilm1_idx` (`tbFilm_film_id` ASC),
  CONSTRAINT `fk_tbJadwal_tbFilm1`
    FOREIGN KEY (`tbFilm_film_id`)
    REFERENCES `dbCinema`.`tbFilm` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbTiket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbTiket` (
  `tiket_id` INT NOT NULL,
  `tiket_harga` DOUBLE NULL,
  `tiket_nomor_kursi` INT NULL,
  `tbMember_member_id` INT NOT NULL,
  `tbStudio_studio_id` INT NOT NULL,
  `tbJadwal_jadwal_id` INT NOT NULL,
  PRIMARY KEY (`tiket_id`, `tbJadwal_jadwal_id`),
  INDEX `fk_tbTiket_tbMember1_idx` (`tbMember_member_id` ASC),
  INDEX `fk_tbTiket_tbStudio1_idx` (`tbStudio_studio_id` ASC),
  INDEX `fk_tbTiket_tbJadwal1_idx` (`tbJadwal_jadwal_id` ASC),
  CONSTRAINT `fk_tbTiket_tbMember1`
    FOREIGN KEY (`tbMember_member_id`)
    REFERENCES `dbCinema`.`tbMember` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbTiket_tbStudio1`
    FOREIGN KEY (`tbStudio_studio_id`)
    REFERENCES `dbCinema`.`tbStudio` (`studio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbTiket_tbJadwal1`
    FOREIGN KEY (`tbJadwal_jadwal_id`)
    REFERENCES `dbCinema`.`tbJadwal` (`jadwal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbGenre` (
  `genre_id` INT NOT NULL,
  `genre_kategori` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbUser` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(100) NULL,
  `user_password` VARCHAR(100) NULL,
  `user_role` VARCHAR(45) NULL,
  `user_name` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbFilm_has_tbGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbFilm_has_tbGenre` (
  `tbFilm_film_id` INT NOT NULL,
  `tbGenre_genre_id` INT NOT NULL,
  PRIMARY KEY (`tbFilm_film_id`, `tbGenre_genre_id`),
  INDEX `fk_tbFilm_has_tbGenre_tbGenre1_idx` (`tbGenre_genre_id` ASC),
  INDEX `fk_tbFilm_has_tbGenre_tbFilm_idx` (`tbFilm_film_id` ASC),
  CONSTRAINT `fk_tbFilm_has_tbGenre_tbFilm`
    FOREIGN KEY (`tbFilm_film_id`)
    REFERENCES `dbCinema`.`tbFilm` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbFilm_has_tbGenre_tbGenre1`
    FOREIGN KEY (`tbGenre_genre_id`)
    REFERENCES `dbCinema`.`tbGenre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCinema`.`tbTransaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbCinema`.`tbTransaksi` (
  `transaksi_id` INT NOT NULL,
  `transaksi_totalprice` VARCHAR(45) NULL,
  `transaksi_payment_method` INT NULL,
  PRIMARY KEY (`transaksi_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
